sudo: required
dist: trusty

compiler:
    - clang

git:
    submodules: false

before_install:
    - git submodule update --init --recursive
    - sudo apt-get update -qq
    - sudo apt-get install -qq clang-3.6 cmake

env:
    global:
        - CXX=clang++-3.6
        - CC=clang-3.6

before_script:
    - mkdir -p tests/build
    - cd tests/build

script:
    - cmake ../
    - make
    - ./brewtrollerTests